language: node_js
node_js: node
cache: npm
before_deploy:
  - npm install -g now
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    repo: abandisch/gym-tracker-server
services:
- mongodb
global: 
  secure: "j/kZzyp6rIyxycE5HA1liQgyE+zRRat39M4XH7uAskiCmB7HAc6eYJL4+CR6407HXKv1J8uVgGbw4B/ti8WSKoQOwlrtYHYdM+Sl+BnRc4TJMWeb8M7iB2q/XkpKRO+kr9Z3NRcFCThfea5NoK531WGb9b5xJAAXB8Te4c9BOV8eAPkvz4+CaQa7JoY8VY1mL6z4e8rCnxMrQZh+OwYJNAqavKx6apNqLHaIq/s9wwRgBXTsDOhQNMECS0n2OJIKkBEgyFh9Lq+J2I4zZHWmcBGV8MquBYOy6NJOnJUYHkUW+8XGO/xgXlIfmNkVy3ApFBRreSLuL9c3YLsZHogRC3BK5sSg5Gbm6ISDGmQIm4/4pKT0xTa6tBnYYIZjV8aiW+E8ghNIjH7atn1tcFjevbiVZxw0zfyBl6NuxkRH3fQrtHFJL3aUf8R+7HbWbzxBhint3lyRSLxkQVwjqWX6SKFqGiFqwarT5Lx5luEIn3OkBUmwnPiekhsTYRMFroKQT90KymvxIFuOfoCMf+RG89mgav2XFtm1ae/yB6e4zVtET3Jyf5pILoqDakERYeoVdRJlijk/+hlSLxG55mnnu7X+P4M/FYH9fnvdCT2kr4jVAYaiCPx80teI1nJRz99bUREwb9hLCXGiqJE5NRTtRGIyk/LqvnKzdd7glVI+fmA="