language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: qsNeOTKVN7zoOkimxkiwVQt++ZeUEJBl3vVbDKl5zQH6QPwU1/1jbK2lCYIIuBBtnA4yLhpMN7n/FvsMTTfBEpn6F+7HCJNjmOe0o7osMSpdv1BAhhl8k1SJ5b9TyTAQZX9TQK+h55fAoBxwKY83BwQYPdAWX1dlfF2z0vMmXX9+opYh7NdYBRSSXH1Piq63vfRA/SPux8kaEpcdy/mvQk+9LNFQEfSmKOjRgx9NaaPhu+e6HATsEbN9Df0Tl9XWSW1dUxGDtDcFHUqzqNxwseGYxJuTVb9Bpo12SucaacOj23CK43LBYzxo4+FVQ5qvmeFiD85GRF9kXSH5crd99HytE7joeILd0fWFHaR3UnpL5xIHyVaKpvbMyz16IxUykqpmo85wPISJElm5tYFLbUZOnT87oCaF827J779nRD0+8Dd3krt91sVuALrgXHvZqzoq7ZZYsmoVY3VwFwXF7vekO/RnNHZT7jI7o9/6Zz7vA9oDZHcEd6C81OMmH2dDCPSKakO0jLmc4DqAHXKr4+XgrFW23qESMT4aAuRor1TSE5KW0cajqZBLFzmQC1mmnvhXddhTdsyIiHooUVXZ04zerYLw9mhwJ810nFkvpraVJ6m4xsztTgDpo9PO5MoX+MhjSpe1bXALckDF6Dp+JUQZ+me/ZO6LADwiDFRVs/M=
  app: gym-tracker-server
  on:
    repo: abandisch/gym-tracker-server
services:
- mongodb
