language: node_js
node_js: node
cache: npm
before_deploy:
  - npm install -g now
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    repo: abandisch/gym-tracker-server
services:
- mongodb
